// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TexturePig.MineClient;
//
//    

namespace TexturePig.MineClient
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class McMeta
    {
        [JsonProperty("pack")]
        public Pack Pack { get; set; }
    }

    public partial class Pack
    {
        [JsonProperty("pack_format")]
        public long PackFormat { get; set; }

        [JsonProperty("description")]
        public string Description { get; set; }
    }

    public partial class McMeta
    {
        public static McMeta FromJson(string json)
        {
            return JsonConvert.DeserializeObject<McMeta>(json, TexturePig.MineClient.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this McMeta self)
        {
            return JsonConvert.SerializeObject(self, TexturePig.MineClient.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
