// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using TexturePig.API;
//
//    var getPack = GetPack.FromJson(jsonString);

namespace TexturePig.API
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class GetPack
    {
        [JsonProperty("id")]
        public long Id { get; set; }

        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("version")]
        public string Version { get; set; }

        [JsonProperty("count")]
        public long Count { get; set; }

        [JsonProperty("download")]
        public Uri Download { get; set; }
    }

    public partial class GetPack
    {
        public static GetPack[] FromJson(string json)
        {
            return JsonConvert.DeserializeObject<GetPack[]>(json, TexturePig.API.Converter.Settings);
        }
    }

    public static class Serialize
    {
        public static string ToJson(this GetPack[] self)
        {
            return JsonConvert.SerializeObject(self, TexturePig.API.Converter.Settings);
        }
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
